project:
  # type: website
  type: book
  output-dir: docs


book:
  title: "Computational Mathematics II (MATH2731)"
  author: "Dr Andrew Krause & Dr Denis Patterson, Durham University"
  date: "June 2025"
  chapters:
    - index.qmd
    - chap-one.qmd
    - chap-two.qmd
    

format:
  html:
    theme:
      - litera
      # - custom.scss
    fontsize: 1.0em
    callout-appearance: simple
    # callout-icon: false
    minimal: false
    toc: true
    self-contained: true
    title-block-banner: "#68246D"
    title-block-banner-color: white
    include-before:
      <p hidden>
      $$
       \def\eb{\boldsymbol{e}}
       \def\fb{\boldsymbol{f}}
       \def\hb{\boldsymbol{h}}
       \def\xb{\boldsymbol{x}}
       \def\Rb{\boldsymbol{R}}
       \def\Real{\mathbb{R}}
       \def\bfzero{\boldsymbol{0}}
       \newcommand{\ddy}[2]{\frac{\partial{#1}}{\partial{#2}}}
      $$
      </p>

  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex
    include-in-header:
      text: |
       \usepackage[makeroom]{cancel}
       \def\eb{\boldsymbol{e}}
       \def\fb{\boldsymbol{f}}
       \def\hb{\boldsymbol{h}}
       \def\xb{\boldsymbol{x}}
       \def\Rb{\boldsymbol{R}}
       \def\Real{\mathbb{R}}
       \def\bfzero{\boldsymbol{0}}
       \newcommand{\ddy}[2]{\frac{\partial{#1}}{\partial{#2}}}
       \DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
       \DeclareOldFontCommand{\rm}{\normalfont\rmseries}{\mathrm}


filters:
  - custom-numbered-blocks

custom-numbered-blocks:
  classes:
    eg:
      collapse: False
      boxstyle: foldbox.simple
      colors: [E7D6EA, 68246D]
      label: Example
    doit:
      collapse: False
      boxstyle: foldbox.simple
      colors: [e7efea, 53b57b]
      label: Exercise
    algorithm:
      collapse: False
      boxstyle: foldbox.simple
      colors: [e7efea, 53b57b]
      label: Algorithm
    theorem:
      collapse: False
      boxstyle: foldbox.simple
      colors: [fcebee, ea3342]
      label: Theorem
    proof:
      collapse: True
      boxstyle: foldbox.simple
      colors: [fcebee, ea3342]
      label: Proof
