project:
  output-dir: _output
  
format:
  html:
    theme:
      - litera
      - custom.scss
    fontsize: 0.9em
    callout-appearance: simple
    minimal: true
    toc: false
    self-contained: true
    title-block-banner: "#EDF7F1"
    include-before:
      <p hidden>
      $$
       \def\eb{\boldsymbol{e}}
       \def\fb{\boldsymbol{f}}
       \def\hb{\boldsymbol{h}}
       \def\xb{\boldsymbol{x}}
       \def\Rb{\boldsymbol{R}}
       \def\Real{\mathbb{R}}
       \def\bfzero{\boldsymbol{0}}
       \newcommand{\ddy}[2]{\frac{\partial{#1}}{\partial{#2}}}
      $$
      </p>

  pdf:
    documentclass: scrartcl
    toc: false
    pdf-engine: pdflatex
    papersize: a4
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - heightrounded
    include-in-header:
      text: |
       \usepackage[makeroom]{cancel}
       \def\eb{\boldsymbol{e}}
       \def\fb{\boldsymbol{f}}
       \def\hb{\boldsymbol{h}}
       \def\xb{\boldsymbol{x}}
       \def\Rb{\boldsymbol{R}}
       \def\Real{\mathbb{R}}
       \def\bfzero{\boldsymbol{0}}
       \newcommand{\ddy}[2]{\frac{\partial{#1}}{\partial{#2}}}
       \DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
       \DeclareOldFontCommand{\rm}{\normalfont\rmseries}{\mathrm}
format-links: false


